#!/usr/bin/env bash
#
# wfmtr
# Webfaction M&M Stack
# Mongo/Node/Meteor Install/Deploy/Run Script
#


function usage() {
  case "$1" in
    "simple")
      echo -e " Usage: wfmtr [deploy|bundle|update|run|stop|startdb] <APP NAME>"
      ;;
    "complex")
      echo -e " Usage: wfmtr [deploy|bundle|update|run|stop|startdb] <APP NAME>"
      ;;
    *)
      echo -e " Usage: wfmtr [deploy|bundle|update|run|stop|startdb] <APP NAME>"
      ;;
  esac
  exit 1
}


# NODE DIST INFORMATION
NODE_VERSION="0.10.36"
NODE_DL_URL="http://nodejs.org/dist/v{node_version}/node-v${NODE_VERSION}.tar.gz"
NODE_REPO="http://mirrors.kernel.org/fedora-epel/6/${ARCH}"
NODE_RPMS=( "nodejs-0.10.36-3.el6.${ARCH}.rpm" "npm-1.3.6-5.el6.noarch.rpm" )
# latest from here...
# http://mirrors.kernel.org/fedora-epel/6/x86_64/
# nodejs-0.10.36-3.el6.i686.rpm
# npm-1.3.6-5.el6.noarch.rpm

# MONGO DIST INFORMATION
MONGO_VERSION="2.6.6"
MONGO_PREFIX="mongodb-linux-x86_64"
MONGO_DIR="${MONGO_PREFIX}-${MONGO_VERSION}"
MONGO_TARBALL="${MONGO_PREFIX}-${MONGO_VERSION}.tgz"
MONGO_DL_URL="http://downloads.mongodb.org/linux/${MONGO_TARBALL}"
MONGO_REPO="http://downloads-distro.mongodb.org/repo/redhat/os/${ARCH}/RPMS"
MONGO_RPM_PREFIX="mongodb-org-"
MONGO_RPMS=( "mongos" "tools" "server" "shell" )


# SYSTEM INFORMATION
CWD=$(pwd)
ARCH=`arch`
IP_ADDRESS=`ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/'`
SERVER_DOMAIN=`hostname -d`
SERVER_NAME=`hostname -s`
SERVER_NAME=${SERVER_NAME^}
SERVER_FQDN=`hostname -f`


# WEBFACTION PYTHON API WRAPPERS
# ------------------------------------------------------------------------------------------

function py_server_connect() {
  # takes username, password, server as input
  # eg. py_server_connect bob secret Web333
  pyStr="import xmlrpclib
server=xmlrpclib.ServerProxy('https://api.webfaction.com/')
session_id, account=server.login(\"${1}\",\"${2}\",\"${3^}\")
"
  echo "${pyStr}"
}


function py_create_app() {
  # takes app name as input
  # eg. py_delete_app myGreatApp
  pyStr="
server.create_app(session_id, \"$1\", 'custom_websockets_app_with_port')
"
  echo "${pyStr}"
}


function py_checkAppExists() {
  # takes app name as string
  # eg. py_checkAppExists myGreatApp
  pyStr="
print 1 if any(app['name']==\"$1\" for app in server.list_apps(session_id)) else 0
"
  echo "${pyStr}"
}


function py_appPort() {
  # takes app name as input
  # eg. py_appPort myGreatApp
  pyStr="
print ([app['port'] for app in server.list_apps(session_id) if app['name']=='$1'] or [0])[0]
"
  echo "${pyStr}"
}


function py_delete_app() {
  # takes app name as input
  # eg. py_delete_app myGreatApp

  pyStr="
server.delete_app(session_id,'$1')
"
  echo "${pyStr}"
}


function py_create_domain() {
  # takes tld, subdomain as input
  # eg. py_create_domain mysite.com www
  pyStr="
server.create_domain(session_id, '$1', '$2')
"
  echo "${pyStr}"
}


function py_domainExists() {
  # takes tld as string
  # eg. py_domainExists mysite.com
  pyStr="
print 1 if any(tld['domain']=='$1' for tld in server.list_domains(session_id)) else 0
"
  echo "${pyStr}"
}


function py_subdomainExists() {
  # takes subdomain and fqdn as string
  # eg. py_subdomainExists www mysite.com
  pyStr="
print 1 if ('$1' in ([domain['subdomains'] for domain in server.list_domains(session_id) if domain['domain']=='$2'] or ['randomstring'])[0]) else 0
"
  echo "${pyStr}"
}


function py_websiteExists() {
  # takes subdomain and fqdn as string
  # eg. py_subdomainExists www mysite.com
  pyStr="
print 1 if any(website['name']=='$1' for website in server.list_websites(session_id)) else 0
"
  echo "${pyStr}"
}


function py_create_website() {
  # takes site name, ip, one domain, appname as input
  # eg. py_create_website myGreatSite 1.1.1.1 mysite.com myGreatApp
  pyStr="
server.create_website(session_id, '$1', '$2', False, ['$3'], ['$4', '/'])
"
  echo "${pyStr}"
}


function py_websiteExists() {
  # takes app name as string
  # eg. py_checkAppExists myGreatApp
  pyStr="
print 1 if any(website['name']=='$1' for website in server.list_apps(session_id)) else 0
"
  echo "${pyStr}"
}


function py_delete_website() {
  # takes site name, ip as input
  # eg. py_delete_website myGreatSite 1.1.1.1
  pyStr="
server.delete_website(session_id, '$1', '$2', False)
"
  echo "${pyStr}"
}


# UTILITY FUNCTIONS
# ------------------------------------------------------------------------------------------

function is_dir() {
  if [ -d "$1" ]; then
    return 0
  else
    return 1
  fi
}


function is_var() {
  # input should be like $MY_VAR
  if [ -n "$1" ]; then
    return 1
  else
    return 0
  fi
}


function get_tld() {
  # input is fqdn
  # eg. get_tld www.mysite.com
  #     returns mysite.com
  echo $1 | sed -r 's/(.*)(\.)([^.]+\.[^.]+)$/\3/'
}


function get_subdomain() {
  # input is fqdn
  # eg. get_tld www.mysite.com
  #     returns www
  echo $1 | sed -r 's/(.*)(\.)([^.]+\.[^.]+)$/\1/'
}


function extractRPMs() {
  for $RPM in rpms/*.rpm; do
    rpm2cpio ${RPM} | cpio -idmv
  done
}


function updatePath() {
  # updates PATH and rehash
  # eg. updatePath $HOME/bin
  #
  NEWPATH=$1
  if [[ ":$PATH:" != *":$NEWPATH:"* ]]; then
  echo 'export PATH=${NEWPATH}:${PATH}' >> ~/.bashrc
  fi
  hash -r
}




function joinLines() {
  # takes a bunch of strings
  # and joins them on new lines
  # eg joinLines "string" "$(function)" "# end"
  # Note: to retain the new line you must quote when echoing
  stringArray=(${@})
  retStr=$( IFS=$'\n'; echo "${stringArray[*]}" )
  echo "$retStr"
}


function confirm() {
  # takes an action description as input
  # eg. confirmAction "melt butter"
  #     Do you want to melt butter? [y/N]
  # if confirm "melt butter"; then
  #  echo "Melting butter."
  # else
  #  echo "Doing Nothing"
  # fi
  read -e -p "Do you want to ${1}? [y/n]> " -n 1
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    true
  else
    false
  fi
}



# GETTER FUNCTIONS
# ------------------------------------------------------------------------------------------

function getPassword() {
  unset PASSWORD
  prompt="Enter your PASSWORD: "
  while IFS= read -p "$prompt" -r -s -n 1 char; do
    if [[ $char == $'\0' ]]; then
      break
    fi
    prompt='*'
    PASSWORD+="$char"
  done
  echo "$PASSWORD"
}


function getAppName() {
  read -e -p "Enter your APP_NAME: " -i "myapp" APP_NAME
  echo "$APP_NAME"
}


function getRootURL() {
  read -e -p "Enter your ROOT_URL: " -i "http://${APP_NAME}.com" ROOT_URL
  echo "$ROOT_URL"
}


function getAppPort() {
  read -e -p "Enter your PORT: " -i "3000" PORT
  echo "$PORT"
}


function getGitUrl() {
  read -e -p "Enter your GIT_URL: " -i "git@bitbucket.org:${USER}/${APP_NAME}.git" GIT_URL
  echo "$GIT_URL"
}


function getGitBranch() {
  read -e -p "Enter your GIT_BRANCH: " -i "master" GIT_BRANCH
  echo "$GIT_BRANCH"
}


function getMailUrl() {
  read -e -p "Enter your MAIL_URL: " -i "smtp://localhost" MAIL_URL
  echo "$MAIL_URL"
}


function getMongoUrl() {
  read -e -p "Enter your MONGO_URL: " -i "mongodb://localhost:${MONGO_PORT}/${APP_NAME}" MONGO_URL
  echo "$MONGO_URL"
}


# MAIN FUNCTIONS
# ------------------------------------------------------------------------------------------


function initEnv() {
  USER_BIN="$HOME/bin"
  USER_WFMTR="$HOME/.wfmtr"
  REQDIRS=( "bin" "lib" "tmp" "src" "include" "lib/pkgconfig" )
  for REQDIR in "${REQDIRS[@]}"; do
    [[ -d "$REQDIR" ]] || mkdir $USER_BIN
  done
  updatePath $HOME/bin
  hash -r
}


function installNode() {
  # takes prefix as input
  # eg. installNode $HOME
  PREFIX=$1
  cd $PREFIX/src
  NODE_VERSION=v0.10.36
  NODE_DIR=node-${NODE_VERSION}
  [ -d "$NODE_DIR" ] && rm -rf $NODE_DIR
  wget http://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}.tar.gz
  tar zxf node-${NODE_VERSION}.tar.gz
  # git clone https://github.com/joyent/node.git
  cd $NODE_DIR
  ./configure --prefix=$PREFIX
  make
  make install
  cd
  npm install -g forever mailchimp less demeteorizer
  #npm install -g node-gyp
  #ln -s $PREFIX/lib/node_modules/node-gyp/bin/node-gyp.js $PREFIX/bin/node-gyp
  #npm install -g fibers
  echo "Installed Node.js"
}


function installMongo() {
  cd $1/src
  wget $MONGO_DL_URL
  tar zxf $MONGO_TARBALL
  cd $MONGO_DIR/bin
  for MNGBIN in *; do
    [ ! -f $HOME/bin/$MNGBIN ] && cp -v $MNGBIN $HOME/bin/
  done
}


function installMeteor() {
  # takes prefix as input
  # eg. installMeteor $HOME/webapps/myGreatApp
  # Note: Node must already be installed!!!
  PREFIX=$1
  cd $PREFIX/src
  rm install_meteor.sh
  wget https://install.meteor.com -O install_meteor.sh
  sed -i "s/^PREFIX=.*$/PREFIX=${PREFIX//\//\\/}/g" install_meteor.sh
  sh install_meteor.sh
  cd
}


function createPlaceholderApp() {
  APP_NAME=$1
  APP_DIR=$HOME/webapps/$APP_NAME
  cd $HOME/tmp
  rm -rf $APP_NAME
  meteor create $APP_NAME
  rsync -av $APP_NAME/ $APP_DIR/
  rm -rf $APP_NAME
  cd
}


function initMeteorApp() {
  # takes repo url as input
  # eg initMeteorApp git@bitbucket.org:username/repo.git
  pushd $HOME/tmp >/dev/null
  REPO="$1"
  APP="$2"
  APPDIR="$HOME/webapps/$APP"
  STAMP="$(date +%s)"
  CLONE="${APP}-${STAMP}"
  # echo $REPO $APP $APPDIR $APPDIR $CLONE
  if confirm "clone repo"; then
    git clone "${REPO}" "${CLONE}"
  fi
  if confirm "rsync and replace with the cloned repo"; then
    rsync -a --delete ${CLONE}/ ${APP_DIR}/
  fi
  popd >/dev/null
}


function updateMeteorApp() {
  # takes repo url as input
  # eg initMeteorApp git@bitbucket.org:username/repo.git
  git pull
}


function configExists() {
  if [ -d "$HOME/.wfmtr/$1" ]; then
    true
  else
    false
  fi
}

function checkAppExists() {
  if [ -d "$HOME/webapps/$1" ]; then
    true
  else
    false
  fi
}


function checkWebsiteExists() {
  WEBSITE_NAME="$1"
  pyCmdStr="$( py_websiteExists $USER $PASSWORD ${SERVER_NAME^} )"
  pyCmdStr+="$( py_websiteExists $WEBSITE_NAME )"
  #echo "$pyCmdStr"
  pyCmd=$( python -c "${pyCmdStr}" )
  echo $pyCmd
}


function bs_createApp() {
  pyCmdStr="$( py_server_connect $USER $PASSWORD ${SERVER_NAME^} )"
  pyCmdStr+="$( py_create_app $1 )"
  #echo "$pyCmdStr"
  pyCmd=$( python -c "${pyCmdStr}" )
  echo $pyCmd
}


function bs_deleteApp() {
  pyCmdStr="$( py_server_connect $USER $PASSWORD ${SERVER_NAME^} )"
  pyCmdStr+="$( py_delete_app $1 )"
  pyCmd=$( python -c "${pyCmdStr}" )
  echo $pyCmd
}


function bs_createWebsite() {
  pyCmdStr="$( py_server_connect $USER $PASSWORD ${SERVER_NAME^} )"
  pyCmdStr+="$( py_create_website $1 $2 $3 $4 )" # myGreatSite 1.1.1.1 mysite.com myGreatApp
  #echo "$pyCmdStr"
  pyCmd=$( python -c "${pyCmdStr}" )
  echo $pyCmd
}


function bs_deleteWebsite() {
  pyCmdStr="$( py_server_connect $USER $PASSWORD ${SERVER_NAME^} )"
  pyCmdStr+="$( py_delete_website $1 $2 )" # myGreatSite 1.1.1.1
  pyCmd=$( python -c "${pyCmdStr}" )
  echo $pyCmd
}


function bs_appPort() {
  pyCmdStr="$( py_server_connect $USER $PASSWORD ${SERVER_NAME^} )"
  pyCmdStr+="$( py_appPort $1 )"
  pyCmd=$( python -c "${pyCmdStr}" )
  echo $pyCmd
}

function bs_dependencies() {
  echo -e "You may have already installed these so skip as you feel necessary."
  echo -e "You DO need all of them though if not previously installed."
  if confirm "install Node.js"; then
    installNode $HOME
  fi
  if confirm "install MongoDB"; then
    installMongo $HOME
  fi
  if confirm "install Meteor"; then
    installMeteor $HOME
  fi
}


function sourceConfig() {
  APP_NAME="$1"
  APP_CONFIG="$HOME/.wfmtr/${APP_NAME}.conf"
  if [ -f $APP_CONFIG ]; then
    source $HOME/.wfmtr/${APP_NAME}.conf
  else
    echo "ERROR: Config file missing!"
    exit 0
  fi
}


function bootstrap() {
  echo "Let's get started..."
  bs_dependencies
  echo -e "Now the real business...\n"
  PASSWORD="$(getPassword)"
  echo
  APP_NAME="$(getAppName)"
  APP_CONFIG_FILE="$HOME/.wfmtr/$APP_NAME.conf"
  ROOT_URL="$(getRootURL)"
  APP_HOST="${ROOT_URL/http:\/\//}"
  APP_DOMAIN="$(get_tld $APP_HOST)"
  APP_SUBDOMAIN="$(get_subdomain $APP_HOST)"
  # echo "url: $url"
  # echo "  proto: $proto"
  # echo "  user: $user"
  # echo "  host: $host"
  # echo "  path: $path"
  GIT_URL="$(getGitUrl)"
  GIT_BRANCH="$(getGitBranch)"
  MAIL_URL="$(getMailUrl)"
  MONGO_URL=""
  FORCE_CLEAN=true
  BIN_APP_NAME="${APP_NAME}_bin"
  APP_DIR="$HOME/webapps/${APP_NAME}"
  BIN_APP_DIR="$HOME/webapps/${BIN_APP_NAME}"
  APP_PID_FILE=$BIN_APP_DIR/forever.pid
  APP_LOG_FILE=$BIN_APP_DIR/forever.log
  MONGO_PID_FILE=$BIN_APP_DIR/mongod.pid
  MONGO_LOG_FILE=$BIN_APP_DIR/mongod.log
  MONGO_DATA_DIR=$BIN_APP_DIR/data
  if confirm "create the app and support binaries"; then
    for APP in "$APP_NAME" "$BIN_APP_NAME"; do
      if checkAppExists "${APP}"; then
        echo "App ${APP} exists."
        echo -n "  "
        if confirm "replace the app"; then
          [ -f "$APP_CONFIG_FILE" ] && rm $APP_CONFIG_FILE
          bs_deleteApp "$APP"
          bs_createApp "$APP"
        fi
      else
        echo -n "  "
        if confirm "create $APP"; then
          bs_createApp "$APP"
        fi
      fi
    done
  fi
  PORT="$(bs_appPort ${APP_NAME})"
  echo "App port is $PORT."
  echo
  MONGO_PORT="$(bs_appPort ${BIN_APP_NAME})"
  MONGO_URL="mongodb://localhost:${MONGO_PORT}/${APP_NAME}"
  echo "Mongo port is $MONGO_PORT."
  echo
  if confirm "create placeholder app"; then
    createPlaceholderApp $APP_NAME
  fi
  if confirm "write config file"; then
    cat > $APP_CONFIG_FILE <<EOL
export APP_CONFIG_FILE="${APP_CONFIG_FILE}"
export APP_NAME="${APP_NAME}"
export APP_DIR="${APP_DIR}"
export BIN_APP_DIR="${BIN_APP_DIR}"
export ROOT_URL="${ROOT_URL}"
export APP_HOST="${APP_HOST}"
export APP_DOMAIN="${APP_DOMAIN}"
export APP_SUBDOMAIN="${APP_SUBDOMAIN}"
export PORT=${PORT}
export MONGO_PORT=${MONGO_PORT}
export GIT_URL="${GIT_URL}"
export GIT_BRANCH="${GIT_BRANCH}"
export MAIL_URL="${MAIL_URL}"
export MONGO_URL="${MONGO_URL}"
export FORCE_CLEAN=${FORCE_CLEAN}
export NODE_ENV="production"
export APP_LOG_FILE="${APP_LOG_FILE}"
export APP_PID_FILE="${APP_PID_FILE}"
export MONGO_LOG_FILE="${MONGO_LOG_FILE}"
export MONGO_PID_FILE="${MONGO_PID_FILE}"
export MONGO_DATA_DIR="${MONGO_DATA_DIR}"
EOL
  ln -s $APP_CONFIG_FILE $BIN_APP_DIR/$APP_NAME.conf
  echo -e "Config file written to ${HOME}/.wfmtr/${APP_NAME}.conf\n"
  fi
  echo -e "\nBootstrap complete."
}


function bundle() {
  APP_NAME="$1"
  sourceConfig $APP_NAME
  pushd $APP_DIR > /dev/null
  if [ -f settings.json ]; then
    SETTINGS_JSON="${APP_DIR}/settings.json"
    if confirm "use your settings.json"; then
      METEOR_SETTINGS="$(cat settings.json)"
      export METEOR_SETTINGS
      cat >> $APP_CONFIG <<EOL
export METEOR_SETTINGS="\$(cat ${SETTINGS_JSON})"
EOL
    echo "Note: currently there's a bug here where the settings get written multiple times."
    echo "      It's not a big deal but if you want to do some housekeeping then remove the duplicates manually."
    fi
  fi
  echo "Note: If you changed your settings.json you need to STOP forever to get the new environment."
  if confirm "bundle the app $APP_NAME"; then
    meteor build --directory $BIN_APP_DIR
  else
    popd > /dev/null
    exit 0
  fi
  popd > /dev/null
  pushd $BIN_APP_DIR/bundle > /dev/null
  (cd programs/server && npm install)
  popd > /dev/null
  echo -e "Meteor app bundled and ready to go."
}


function deploy() {
  APP_NAME="$1"
  (
  sourceConfig $APP_NAME
  PASSWORD="$(getPassword)"
  WEBSITE_DOMAIN="$APP_SUBDOMAIN.$APP_DOMAIN"
  echo
  if [ -f $APP_DIR/.git ]; then
    echo "Site exists. Did you want to update instead?"
    exit 0
  else
    if confirm "init app dir and pull from repo"; then
      initMeteorApp "$GIT_URL" $APP_NAME
    fi
  fi
  if confirm "bundle app for node.js"; then
    bundle $APP_NAME
  fi
  WEBSITE_NAME="${APP_NAME}_site"
  if checkWebsiteExists "$WEBSITE_NAME"; then
    if confirm "delete existing website"; then
      bs_deleteWebsite "$WEBSITE_NAME" "$IP_ADDRESS"
    else
      echo -e "\nYou'll now be asked if you want to update the website."
      echo -e "This is destructive so if you have multiple apps"
      echo -e "running on the site, do this manually using the control panel.\n"
      if confirm "update existing website"; then
        bs_updateWebsite "$WEBSITE_NAME" "$IP_ADDRESS" "$WEBSITE_DOMAIN" "$APP_NAME"
      fi
    fi
  else
    bs_createWebsite "$WEBSITE_NAME" "$IP_ADDRESS" "$WEBSITE_DOMAIN" "$APP_NAME"
  fi
  echo -e "Deployment complete. Now use wfmtr run <app name>."
 )
}


function appRunning() {
  if [ -f "$1" ]; then
    PID="$(cat $1)"
    if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
      true
    else
      rm $APP_PID_FILE
      rm $APP_LOG_FILE
      false
    fi
  else
   false
  fi
}


function startdb() {
  APP_NAME="$1"
  (
  sourceConfig $APP_NAME
  [ ! -d $MONGO_DATA_DIR ] && mkdir -p $MONGO_DATA_DIR
  if [ -e "${MONGO_PID_FILE}" ] && (ps -u $(whoami) -opid= | grep -P "^\s*$(cat ${MONGO_PID_FILE})$" &> /dev/null); then
    echo "Already running."
    exit 99
  fi
  export PIDFILE=$MONGO_PID_FILE
  $HOME/bin/mongod --noauth --dbpath $MONGO_DATA_DIR --port $MONGO_PORT > $MONGO_LOG_FILE &
  echo "Mongo started."
  )
}


function run() {
  APP_NAME="$1"
  (
  sourceConfig "$1"
  if [ ! -d $BIN_APP_DIR/bundle ]; then
    echo "ERROR: No bundle exists! Run update or deploy."
    exit 0
  fi
  if appRunning $APP_PID_FILE; then
    echo "ERROR: App is running. PID $(cat $APP_PID_FILE)."
    exit 0
  fi
  startdb $APP_NAME
  # set -a
  # . $APP_CONFIG_FILE
  # set +a
  forever restart --pidfile $APP_PID_FILE --append \
  -l $APP_LOG_FILE -o $BIN_APP_DIR/out.log -e $BIN_APP_DIR/err.log \
  $BIN_APP_DIR/bundle/main.js || \
  forever start --pidfile $APP_PID_FILE --append \
  -l $APP_LOG_FILE -o $BIN_APP_DIR/out.log -e $BIN_APP_DIR/err.log \
  $BIN_APP_DIR/bundle/main.js
  echo -e "Application $APP_NAME is running."
  )
}


function stop() {
  APP_NAME="$1"
  (
  sourceConfig "$1"
  if [ ! -d $BIN_APP_DIR/bundle ]; then
    echo "ERROR: No bundle exists! Run update or deploy."
    exit 0
  fi
  #if appRunning $APP_PID_FILE; then
  #  echo "ERROR: App is running. PID $(cat $APP_PID_FILE)."
  #  exit 0
  #fi
  # set -a
  # . $APP_CONFIG_FILE
  # set +a
  forever stop --pidfile $APP_PID_FILE -l $APP_LOG_FILE $BIN_APP_DIR/bundle/main.js
  echo -e "Application $APP_NAME is stopped."
  )
}


[[ $# -eq 0 ]] && usage
if [[ $# -eq 1 ]]; then
  case "$1" in
    "bootstrap")
      bootstrap
    ;;
    *)
      usage simple
    ;;
  esac
  exit 1
fi


if [[ $# -eq 2 ]]; then
  if [ ! -d $HOME/webapps/$2 ]; then
    echo "Site does not exist."
    exit 1
  else
    APP_NAME="$2"
    case "$1" in
      "deploy")
        deploy ${APP_NAME}
      ;;
      "bundle")
        bundle ${APP_NAME}
      ;;
      "update")
        update ${APP_NAME}
      ;;
      "run")
        run ${APP_NAME}
      ;;
      "stop")
        stop ${APP_NAME}
      ;;
      "restart")
        stop ${APP_NAME}
        run ${APP_NAME}
      ;;
      "startdb")
        startdb ${APP_NAME}
      ;;
      *)
        usage complex
      ;;
    esac
    exit 1
  fi
else
  usage
fi


